# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e83c1932c3684dc31684493336bfc177870bbf3183671f5aa863837a1314453d17c1a09866c784870584716406f6886124b31b6025783a2e7a0ce644d53e44d3

test:
  secret_key_base: 716f81eb762b14ed611d0457df77030a16c1bd25abbba7481950ca2d0765dea306ea363ac00aff18aa04e9f3652b096c53e71fce3a754fa47a364ca9c24a7320

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
